# Generated by Django 4.1 on 2022-08-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_alter_forex_destinationcurrency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forex',
            new_name='ForexConvert',
        ),
    ]
